accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order'),
    path('order/<int:order_id>', views.order_detail, name='order_detail'),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
	path('product/', views.product, name='product'),
	path('contact/', views.contact, name='contact'),
	path('contact/feedback', views.feedback, name='feedback'),
 	path('about-us/', views.about_us, name='about_us'),
]

orders/models.py
from django.db import models

from accounts.models import User
from shop.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.full_name} - order id: {self.id}"

    @property
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        return total
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST
from django.utils import timezone

from .models import Order, OrderItem
from cart.utils.cart import Cart

@login_required
def create_order(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(
            order=order, product=item['product'],
            price=item['price'], quantity=item['quantity'])
    return redirect('orders:pay_order', order_id=order.id)


@login_required
def checkout(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Checkout' ,'order':order}
    return render(request, 'checkout.html', context)


@login_required
def fake_payment(request, order_id):
    cart = Cart(request)
    cart.clear()
    order = get_object_or_404(Order, id=order_id)
    order.status = True
    order.save()
    return redirect('orders:user_orders')


@login_required
def user_orders(request):
    orders = request.user.orders.all()
    context = {'title':'Orders', 'orders': orders}
    return render(request, 'user_orders.html', context)

@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Chi tiết đơn hàng' ,'order':order}
    return render(request, 'order_detail.html', context)

orders/templates/checkout.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-2"></div>

<div class="col-md-8 border rounded p-3">
    <h3 class="text-muted">Your Order Amount is: ${{order.get_total_price}}</h3>
    <hr>
    <p><b>Do you want to continue and pay?</b></p>
    <a href="{% url 'cart:show_cart' %}" class="btn btn-danger">Back To Cart</a>
    <a href="{% url 'orders:create_order' %}" class="btn btn-outline-success">Continue and pay</a>
<div class="col-md-2"></div>

{% endblock %}

orders/templates/order_detail.html
{% extends "base.html" %}

{% block extend_page %}

<section class="py-5">
    <div class="container py-4">
      <div class="row gy-5">
        <div class="col-lg-9">
            <p class="lead mb-4">Đơn hàng #{{ order.id }} được tạo <strong>{{ order.created }}</strong> với trạng thái 
                {% if order.status %}
                    <strong class="text-success">Hoàn thành</strong>.
                {% else %}
                    <strong class="text-danger">Bị hủy</strong>.
                {% endif %}
            </p>
          {% comment %} <p class="lead text-muted mb-5">If you have any questions, please feel free to <a href="contact.html">contact us</a>, our customer service center is working for you 24/7.</p> {% endcomment %}
          <!-- ORDER TABLE-->
          <div class="table-responsive">
            <table class="table text-nowrap">
              <thead>
                <tr class="text-sm">
                  <th class="border-gray-300 border-top py-4" colspan="2">Product</th>
                  <th class="border-gray-300 border-top py-4">Quantity</th>
                  <th class="border-gray-300 border-top py-4">Unit price</th>
                  <th class="border-gray-300 border-top py-4">Total</th>
                </tr>
              </thead>
              <tbody>
                {% for item in order.items.all %}
                    <tr class="text-sm">
                        <td class="align-middle border-gray-300 py-4"><a href="#"><img class="img-fluid flex-shrink-0" src="{{item.product.image.url}}" alt="White Blouse Armani" style="min-width: 50px" width="50"></a></td>
                        <td class="align-middle border-gray-300 py-4"><a href="{{ item.product.get_absolute_url }}">{{item.product.title}}</a></td>
                        <td class="align-middle border-gray-300 py-4">{{item.quantity}}</td>
                        <td class="align-middle border-gray-300 py-4">${{item.price}}</td>
                        <td class="align-middle border-gray-300 py-4">${{item.get_cost}}</td>
                    </tr>
                {% endfor %}
              </tbody>
              <tfoot>
                <tr>
                  <th class="text-end lead py-3" colspan="5">Phí vận chuyển</th>
                  <th class="lead py-3">Miễn phí</th>
                </tr>
                {% comment %} <tr>
                  <th class="text-end lead py-3" colspan="5">Thuế</th>
                  <th class="lead py-3">$0.00</th>
                </tr> {% endcomment %}
                <tr>
                  <th class="border-0 text-end lead py-3" colspan="5">Tổng tiền</th>
                  <th class="border-0 lead py-3">${{ order.get_total_price }}</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
        <div class="col-lg-3">
          <h3 class="h4 text-uppercase lined mb-4">Khách hàng</h3>
          <nav class="nav flex-column nav-pills">
                <a class="nav-link text-sm active" href="{% url "orders:user_orders" %}"> 
                    <i class="me-2 fa fa-list"></i>
                    <span>Đơn hàng</span>
                </a>
                <a class="nav-link text-sm" href="{% url "shop:favorites" %}"> 
                    <i class="me-2 fa fa-heart"></i>
                    <span>Yêu thích</span>
                </a>
                <a class="nav-link text-sm" href="{% url "accounts:edit_profile" %}"> 
                    <i class="me-2 fa fa-user"></i>
                    <span>Tài khoản</span>
                </a>
                <a class="nav-link text-sm" href="{% url "accounts:user_logout" %}"> 
                    <i class="me-2 fa fa-sign-out"></i>
                    <span>Đăng xuất</span>
                </a>
          </nav>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

orders/templates/user_orders.html
{% extends "base.html" %}

{% block extend_page %}

<section class="py-5">
    <div class="container py-4">
      <div class="row gy-5">
        <div class="col-lg-9">
          {% comment %} <p class="text-muted lead mb-5">If you have any questions, please feel free to <a href="contact.html">contact us</a>, our customer service center is working for you 24/7.</p> {% endcomment %}
          <!-- ORDERS TABLE-->
          <div class="table-responsive">
            <table class="table table-hover text-nowrap">
              <thead>
                <tr class="text-sm">
                  <th class="border-gray-300 border-top py-3">Đơn hàng</th>
                  <th class="border-gray-300 border-top py-3">Thời gian</th>
                  <th class="border-gray-300 border-top py-3">Tổng tiền</th>
                  <th class="border-gray-300 border-top py-3">Trạng thái</th>
                  <th class="border-gray-300 border-top py-3">Hành động</th>
                </tr>
              </thead>
              <tbody>
                {% if orders %}
                {% for order in orders %}
                    <tr class="text-sm">
                        <th class="align-middle py-3"># {{ order.id }}</th>
                        <td class="align-middle py-3">$ {{ order.created }}</td>
                        <td class="align-middle py-3">$ {{ order.get_total_price }}</td>
                        {% if order.status %}
                            <td class="align-middle py-3 text-success">Hoàn thành</td>
                        {% else %}
                            <td class="align-middle py-3 text-danger">Bị hủy</td>
                        {% endif %}
                        <td class="align-middle py-3"><a class="btn btn-outline-primary btn-sm" href="{% url 'orders:order_detail' order.id %}">Xem chi tiết</a></td>
                    </tr>
                {% endfor %}
                {% else %}
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8 mt-5 pt-5 text-center">
                        <br>
                        <h1 class="text-muted text-capitalize">Đơn hàng trống..!</h1>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                {% endif %}
                
                {% comment %} <tr class="text-sm">
                  <th class="align-middle py-3"># 1735</th>
                  <td class="align-middle py-3">22/06/2013</td>
                  <td class="align-middle py-3">$ 150.00</td>
                  <td class="align-middle py-3"><span class="badge fw-light text-uppercase bg-info">Being prepared</span></td>
                  <td class="align-middle py-3"><a class="btn btn-outline-primary btn-sm" href="customer-order.html">View</a></td>
                </tr>
                <tr class="text-sm">
                  <th class="align-middle py-3"># 1735</th>
                  <td class="align-middle py-3">22/06/2013</td>
                  <td class="align-middle py-3">$ 150.00</td>
                  <td class="align-middle py-3"><span class="badge fw-light text-uppercase bg-primary">Received</span></td>
                  <td class="align-middle py-3"><a class="btn btn-outline-primary btn-sm" href="customer-order.html">View</a></td>
                </tr>
                <tr class="text-sm">
                  <th class="align-middle py-3"># 1735</th>
                  <td class="align-middle py-3">22/06/2013</td>
                  <td class="align-middle py-3">$ 150.00</td>
                  <td class="align-middle py-3"><span class="badge fw-light text-uppercase bg-danger">Cancelled</span></td>
                  <td class="align-middle py-3"><a class="btn btn-outline-primary btn-sm" href="customer-order.html">View</a></td>
                </tr>
                <tr class="text-sm">
                  <th class="align-middle py-3"># 1735</th>
                  <td class="align-middle py-3">22/06/2013</td>
                  <td class="align-middle py-3">$ 150.00</td>
                  <td class="align-middle py-3"><span class="badge fw-light text-uppercase bg-warning">On hold</span></td>
                  <td class="align-middle py-3"><a class="btn btn-outline-primary btn-sm" href="customer-order.html">View</a></td>
                </tr> {% endcomment %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-lg-3">
          <h3 class="h4 text-uppercase lined mb-4">Khách hàng</h3>
          <nav class="nav flex-column nav-pills">
                <a class="nav-link text-sm active" href=""> 
                    <i class="me-2 fa fa-list"></i>
                    <span>Đơn hàng</span>
                </a>
                <a class="nav-link text-sm" href="{% url "shop:favorites" %}"> 
                    <i class="me-2 fa fa-heart"></i>
                    <span>Yêu thích</span>
                </a>
                <a class="nav-link text-sm" href="{% url "accounts:edit_profile" %}"> 
                    <i class="me-2 fa fa-user"></i>
                    <span>Tài khoản</span>
                </a>
                <a class="nav-link text-sm" href="{% url "accounts:user_logout" %}"> 
                    <i class="me-2 fa fa-sign-out"></i>
                    <span>Đăng xuất</span>
                </a>
          </nav>
        </div>
      </div>
    </div>
  </section>

{% endblock %}