accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order'),
    path('order/<int:order_id>', views.order_detail, name='order_detail'),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
	path('product/', views.product, name='product'),
	path('contact/', views.contact, name='contact'),
	path('contact/feedback', views.feedback, name='feedback'),
 	path('about-us/', views.about_us, name='about_us'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=200)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='category',blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs): # new
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
        

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    image = models.ImageField(upload_to='products',blank=True)
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.slug
        
    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='products')
    
    @classmethod
    def get_ralated_images_by_product_id(cls, id):
        return cls.objects.filter(product_id = id).all().values()
     
class Feedback(models.Model):
    customer_name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    email = models.EmailField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.customer_name 

shop/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['customer_name', 'title', 'email', 'comment']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from shop.models import Product, Category, ProductImage, Feedback
from cart.forms import QuantityForm
from .forms import FeedbackForm

from re import sub

def paginat(request, list_objects, num_list):
	p = Paginator(list_objects, num_list)
	page_number = request.GET.get('page')
	try:
		page_obj = p.get_page(page_number)
	except PageNotAnInteger:
		page_obj = p.page(1)
	except EmptyPage:
		page_obj = p.page(p.num_pages)
	return page_obj

def home_page(request):
	products = Product.objects.all()
	feedback_first = Feedback.objects.first()
	feedbacks = Feedback.objects.all()[-2:]
	context = {'title':'SuccesS','products': paginat(request ,products, 6), 'feedbacks': feedbacks, 'feedback_first': feedback_first}
	return render(request, 'home_page.html', context)

def contact (request):
    return render(request, 'contact.html')

def about_us (request):
    return render(request, 'about_us.html')

def product (request):
    products = Product.objects.all()
    context = {'title':'Điện thoại', 'products': paginat(request ,products, 12)}
    return render(request, 'product.html', context)

def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Đã gửi thông tin thành công', 'success')
            return redirect('shop:contact')
    else:
        form = FeedbackForm()

    return render(request, 'feedback.html', {'form': form})

def product_detail(request, slug):
	form = QuantityForm()
	product = get_object_or_404(Product, slug=slug)
	related_products = Product.objects.filter(category=product.category).all()[:4]
	context = {
		'title':product.title,
		'product':product,
		'form':form,
		'related_images': ProductImage.get_ralated_images_by_product_id(product.id),
		'favorites':'favorites',
		'related_products':related_products
	}
	if login_required == True :
		if request.user.likes.filter(id=product.id).first():
			context['favorites'] = 'remove'
	return render(request, 'product_detail.html', context)


@login_required
def add_to_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.add(product)
	return redirect('shop:favorites')


@login_required
def remove_from_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.remove(product)
	return redirect('shop:favorites')


@login_required
def favorites(request):
	products = request.user.likes.all()
	context = {'title':'Favorites', 'products':products}
	return render(request, 'favorites.html', context)


def search(request):
	query = request.GET.get('q')
	words = sub(r'\s+', ' ', query).strip().split(' ')
	search_query = Q()
	for s in words :
		search_query &= Q(title__icontains=s)
	products = Product.objects.filter(search_query).all()
	context = {'products': paginat(request ,products, 12)}
	return render(request, 'product.html', context)


def filter_by_category(request, slug):
	"""when user clicks on parent category
	we want to show all products in its sub-categories too
	"""
	result = []
	category = Category.objects.filter(slug=slug).first()
	[result.append(product) \
		for product in Product.objects.filter(category=category.id).all()]
	# check if category is parent then get all sub-categories
	if not category.is_sub:
		sub_categories = category.sub_categories.all()
		# get all sub-categories products 
		for category in sub_categories:
			[result.append(product) \
				for product in Product.objects.filter(category=category).all()]
	context = {'title': 'Nhãn hàng: ' + category.title,'products': paginat(request ,result, 12)}
	return render(request, 'product.html', context)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>{% if title %} {{ title }} {% else %} Django Online Shop {% endif %}</title>

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

  
  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:500,800&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"  />

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <!-- responsive style -->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
  {% block css %} {% endblock%}
</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Gọi ngay : 0835792003
                </span>
              </a>
              {% comment %} <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : demo@gmail.com
                </span>
              </a> {% endcomment %}
            </div>
            <form class="search_form" action="{% url 'shop:search' %}">
              <input name="q" type="search" class="form-control form-control-dark" placeholder="Tìm kiếm..." aria-label="Search">
              <button class="" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
            <div class="user_option_box">
              <!-- favorite icon -->
              <a href="{% url 'shop:favorites' %}">
                <i class="fa fa-heart" aria-hidden="true"></i>
                <span>
                  Yêu thích
                </span>
                  {% if request.user.is_authenticated %}
                <div class="pop_up">  
                  {{ request.user.get_likes_count}}
                  <div class="pop_up_after"></div>
                </div>
              {% endif %}
              </a>
              
              
              <div class="dropdown text-end">
                <a href="#" class="dropdown-toggle" id="dropdownUser1" type="button" data-bs-toggle="dropdown" aria-haspopup="true" 
                aria-expanded="true">
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <span class="caret">
                  Tài Khoản
                  </span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
                {% if request.user.is_authenticated %}
                <!-- user profile dropdown -->
                  <li><a href="{% url 'cart:show_cart' %}" <a class="dropdown-item">Giỏ hàng</a></li>
                  <li><a href="{% url 'shop:favorites' %}" <a class="dropdown-item">Yêu thích</a></li>
                  <li><a href="{% url 'orders:user_orders' %}" <a class="dropdown-item">Đơn hàng</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Thông tin</a></li>
                  <li><a class="dropdown-item text-danger" href="{% url 'accounts:user_logout' %}">Đăng xuất</a></li>
                </ul>
              </div>
              {% else %}
              <!-- login, sign-up btn -->
                <li><a href="{% url 'accounts:user_login' %}" class="dropdown-item">Đăng nhập</a></li>
                <li><a href="{% url 'accounts:user_register' %}" class="dropdown-item">Đăng ký</a></li>
              </div> 
              {% endif %}
              <!-- cart icon -->
              <a href="{% url 'cart:show_cart' %}" class="cart-link">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span>
                  Giỏ hàng
                </span>
                {% if request.user.is_authenticated %}
                <div class="pop_up">  
                  {{ cart_count }}
                  <div class="pop_up_after"></div>
                </div>
              {% endif %}
              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <div class="navbar custom_nav-container navbar-expand-lg">
            <a class="navbar-brand" href="{% url 'shop:home_page' %}">
              <span>
                SuccesS
              </span>
            </a>
            <button class="navbar-toggler text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            {% comment %} <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent">
              <span class="navbar-toggler-icon"></span>
            </button> {% endcomment %}

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:home_page' %}">Trang chủ
                    {% comment %} <span class="sr-only">(current)</span> {% endcomment %}
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:product' %}">Sản phẩm</a>
                </li>
                <li class="nav-item dropdown category_dropdown"><a class="nav-link dropdown-toggle" id="contactMegamenu" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Nhãn hàng</a>
                  <ul class="dropdown-menu dropdown-menu-end m-0" aria-labelledby="contactMegamenu">
                    {% for category in categories %}
                    <!-- check if category is parent -->
                      {% if not category.is_sub %}
                      <!-- parent -->
                        <li><a href="{% url 'shop:filter_by_category' category.slug %}" class="dropdown-item text-uppercase">{{ category }}</a></li>
                        {% for child in category.sub_categories.all %}
                        <!-- child -->
                        <li><a href="{% url 'shop:filter_by_category' child.slug %}" class="dropdown-item">{{ child }}</a></li>
                        {% endfor %}
                      {% endif %} 
                    {% endfor %}
                  </ul>
                  {% comment %} <ul class="dropdown-menu dropdown-submenu m-0"> {% endcomment %}
                    
                    {% comment %} <li><a class="dropdown-item text-uppercase border-bottom" href="">Action </a></li>
                    <li><a class="dropdown-item text-uppercase border-bottom" href="">Another action </a></li>
                    <li><a class="dropdown-item text-uppercase border-bottom" href="">Application </a></li>
                    <li><a class="dropdown-item text-uppercase border-bottom" href="">Something else here </a></li> {% endcomment %}
                  {% comment %} </ul> {% endcomment %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:about_us' %}">Về chúng tôi</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:contact' %}">Liên hệ</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
  
    {% block slider %} {% endblock%}
  <main class="container">
    <div class="row mt-3">
      <!-- messages -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      <!-- content -->
      {% block content %}{% endblock %}
    </div>
  </main>
  {% block extend_page %} {% endblock %}

  {% block other_section %} {% endblock %}
  
  <!-- info section -->
<section class="info_section ">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="info_contact">
          <h5>
            <a href="" class="navbar-brand">
              <span>
                SuccesS
              </span>
            </a>
          </h5>
          <p>
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            Viện công nghệ thông tin T3h
          </p>
          <p>
            <i class="fa fa-phone" aria-hidden="true"></i>
            0835792003
          </p>
          <p>
            <i class="fa fa-envelope" aria-hidden="true"></i>
            SuccesSPhone@store.com
          </p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="info_info">
          <h5>
            Giới thiệu
          </h5>
          <p>
            Nhanh gọn, tiện lợi, dễ dàng, đơn giản là những tiêu chí hàng đầu của chúng tôi trong việc cung cấp những sản phẩm và dịch vụ đến
            khách hàng.
          </p>
        </div>
      </div>
      <div class="col-md-3" style="padding-left: 5%">
        <div class="info_links">
          <h5>
            Tiện ích
          </h5>
          <ul>
            <li>
              <a href="{% url 'shop:home_page' %}">
                Trang chủ
              </a>
            </li>
            <li>
              <a href="">
                Nhãn hàng
              </a>
            </li>
            <li>
              <a href="{% url 'shop:product' %}">
                Sản phẩm
              </a>
            </li>
            <li>
              <a href="{% url 'shop:about_us' %}">
                Về chúng tôi
              </a>
            </li>
            <li>
              <a href="{% url 'shop:contact' %}">
                Liên hệ
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <div class="info_form ">
          <h5>
            Nhận thông tin mới nhất 
          </h5>
          <form action="">
            <input type="email" placeholder="Điền email của bạn">
            <button>
              Đăng ký
            </button>
          </form>
          <div class="social_box">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By Cong
      </p>
    </div>
  </footer>
  <!-- footer section -->
  {% block script %} {% endblock %}
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- poper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- bootstrap js  -->
  <script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

shop/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/nice-select.css" %}">
	<link rel="stylesheet" href="{% static "css/contact.css" %}">
{% endblock %}

{% block content %}
<!--================Contact Area =================-->
<section class="contact_area section_gap_bottom">
    <div class="container">
        <div class="heading_container heading_center">
            <h2>
              Liên hệ với chúng tôi
            </h2>
          </div>
        <iframe style="margin-bottom: 5%" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.8698652802823!2d105.7740581!3d21.0378924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313455f90fe8ad65%3A0xec38b94cb36de0ab!2zVmnhu4duIEPDtG5nIG5naOG7hyB0aMO0bmcgdGluIFQzSA!5e0!3m2!1svi!2s!4v1697897268428!5m2!1svi!2s" width="1110" height="420" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>Hà Nội, Việt Nam</h6>
                        <p>Số 128A, Đường Hồ Tùng Mậu, Mai Dịch, Cầu Giấy</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6>0835792003</h6>
                        <p>Thứ 2 - Thứ 6, 9:00 - 16:00</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6><a href="#">support.SuccesS@T3h.com</a></h6>
                        <p>Hãy gửi cho tôi bất cứ lúc nào!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="{% url 'shop:feedback' %}" method="post" id="contactForm" novalidate="novalidate">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="customer_name" placeholder="Nhập tên của bạn" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Điền họ và tên'">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Nhập địa chỉ email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Điền email'">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="title" placeholder="Nhập tiêu đề" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập tiêu đề'">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="comment" id="message" rows="1" placeholder="Hãy điền nội dung" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Hãy điền nội dung'"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="primary-btn">Gửi thông tin</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!--================Contact Area =================-->
{% endblock %}

shop/templates/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="product_section_2 layout_padding">
<div class="container">
  <div class="heading_container heading_center">
    <h2>
      Yêu thích
    </h2>
  </div>
  <div class="row">
    {% if products %}
    {% for product in products %}
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="box">
        <div class="option_container">
            <div class="options">
               <a href="{{ product.get_absolute_url }}" class="option1">
               Mua ngay
               </a>
               <a href="{% url 'shop:remove_from_favorites' product.id %}" class="option2">
                Bỏ yêu thích
               </a>
            </div>
         </div>
        <div class="img-box">
        <img style="object-fit: contain;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}" alt="">
      </div>
        <div class="detail-box">
          <h5 class="card-title">{{ product.title }}</h5>
          <div class="product_info">
            <h6 class="text-muted">
              <span>$</span> {{ product.price }}
            </h6>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- pagination -->
    <center class="mt-5">
      <div class="col-md-2">
        <ul class="pagination">
          {% if products.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">{{products.previous_page_number}}</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="?page={{ products.number }}">{{products.number}}</a></li>
          {% if products.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{products.next_page_number}}</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
          {% endif %}
        </ul>
      </div>
    </center>
    {% else %}
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-5 pt-5  text-center">
          <br>
          <h3 class="text-muted text-capitalize">Danh sách trống..!</h3>
        </div>
        <div class="col-md-2"></div>
      </div>
    {% endif %}

</section>

<!-- end product section -->
{% endblock %}

shop/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="product_section_2 layout_padding">
<div class="container">
  <div class="heading_container heading_center">
    <h2>
      {{ title }}
    </h2>
  </div>
  <div class="row">
    {% if products %}
    {% for product in products.object_list %}
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="box">
        <div class="option_container">
            <div class="options">
               <a href="{{ product.get_absolute_url }}" class="option1">
               Mua ngay
               </a>
               <a href="{% url 'shop:add_to_favorites' product.id %}" class="option2">
                Yêu thích
               </a>
            </div>
         </div>
        <div class="img-box">
        <img style="object-fit: contain;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}" alt="">
      </div>
        <div class="detail-box">
          <h5 class="card-title">{{ product.title }}</h5>
          <div class="product_info">
            <h6 class="text-muted">
              <span>$</span> {{ product.price }}
            </h6>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- pagination -->
    <center class="mt-5">
      <div class="col-md-2">
        <ul class="pagination">
          {% if products.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Trước</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">{{products.previous_page_number}}</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="?page={{ products.number }}">{{products.number}}</a></li>
          {% if products.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{products.next_page_number}}</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Sau</a></li>
          {% endif %}
        </ul>
      </div>
    </center>
    {% else %}
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-5 pt-5  text-center">
          <br>
          <h3 class="text-muted text-capitalize">Sản phẩm không tồn tại..!</h3>
        </div>
        <div class="col-md-2"></div>
      </div>
    {% endif %}

</section>

<!-- end product section -->
{% endblock %}