accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order'),
    path('order/<int:order_id>', views.order_detail, name='order_detail'),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
	path('product/', views.product, name='product'),
	path('contact/', views.contact, name='contact'),
	path('contact/feedback', views.feedback, name='feedback'),
 	path('about-us/', views.about_us, name='about_us'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from .managers import UserManager
from shop.models import Product


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100)    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    likes = models.ManyToManyField(Product, blank=True, related_name='likes')
    # set a manager role for shop manager to access orders and products
    is_manager = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_likes_count(self):
        return self.likes.count()

accounts/forms.py
from django import forms

from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'full name'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class ManagerLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['full_name', 'email']
    
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .forms import UserRegistrationForm, UserLoginForm, ManagerLoginForm, EditProfileForm
from accounts.models import User


def create_manager():
    """
    to execute once on startup:
    this function will call in online_shop/urls.py
    """
    if not User.objects.filter(email="manager@example.com").first():
        user = User.objects.create_user(
            "manager@example.com", 'shop manager' ,'managerpass1234'
        )
        # give this user manager role
        user.is_manager = True
        user.save()


def manager_login(request):
    if request.method == 'POST':
        form = ManagerLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None and user.is_manager:
                login(request, user)
                return redirect('dashboard:products')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger'
                )
                return redirect('accounts:manager_login')
    else:
        form = ManagerLoginForm()
    context = {'form': form}
    return render(request, 'manager_login.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                data['email'], data['full_name'], data['password']
            )
            return redirect('accounts:user_login')
    else:
        form = UserRegistrationForm()
    context = {'title':'Signup', 'form':form}
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('shop:home_page')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger'
                )
                return redirect('accounts:user_login')
    else:
        form = UserLoginForm()
    context = {'title':'Login', 'form': form}
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


def edit_profile(request):
    form = EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your profile has been updated', 'success')
        return redirect('accounts:edit_profile')
    else:
        form = EditProfileForm(instance=request.user)
    context = {'title':'Edit Profile', 'form':form}
    return render(request, 'edit_profile.html', context)

accounts/templates/edit_profile copy.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Edit Profile</h3>
            <hr>
            {{ form|crispy  }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% comment %} <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Edit Profile</h3>
            <hr>
            {{ form|crispy  }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Update</button>
            </div>
        </form>
    </div> {% endcomment %}

<!-- PROFILE DETAIL FORM-->
<section class="py-5">
    <div class="container py-4">
      <div class="row gy-5">
        <div class="col-lg-9">
            <form class="py-4" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 mb-4">
                        <h3 class="text-uppercase lined">Thông tin tài khoản</h3>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label" for="fullname">Họ và tên</label>
                        {{ form.full_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label class="form-label" for="email_account">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="col-lg-12 text-center" style="margin-top: 5%">
                        <button class="btn btn-outline-primary" type="submit"> <i class="fa fa-save me-2"></i>Cập nhật</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3">
            <h3 class="h4 text-uppercase lined mb-4">Khách hàng</h3>
            <nav class="nav flex-column nav-pills">
                <a class="nav-link text-sm " href="{% url "orders:user_orders" %}"> 
                    <i class="me-2 fa fa-list"></i>
                    <span>Đơn hàng</span>
                </a>
                <a class="nav-link text-sm" href="{% url "shop:favorites" %}"> 
                    <i class="me-2 fa fa-heart"></i>
                    <span>Yêu thích</span>
                </a>
                <a class="nav-link text-sm active" href="{% url "accounts:edit_profile" %}"> 
                    <i class="me-2 fa fa-user"></i>
                    <span>Tài khoản</span>
                </a>
                <a class="nav-link text-sm" href="{% url "accounts:user_logout" %}"> 
                    <i class="me-2 fa fa-sign-out"></i>
                    <span>Đăng xuất</span>
                </a>
            </nav>
        </div>
    </div>
</div>
</section>
{% endblock %}

accounts/templates/email_template.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <!-- CSS Files -->
    <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.2/components/logins/login-8/assets/css/login-8.css" />

{% endblock %}
{% block extend_page %}
    <!-- Login 8 - Bootstrap Brain Component -->
    <section class="bg-light p-3 p-md-4 p-xl-5">
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-xxl-11">
            <div class="card border-light-subtle shadow-sm">
                <div class="row g-0">
                <div class="col-12 col-md-6">
                    <img class="img-fluid rounded-start w-100 h-100 object-fit-contain" loading="lazy" src="{% static "images/iphone-15-promax.png" %}" alt="Welcome back you've been missed!">
                </div>
                <div class="col-12 col-md-6 d-flex align-items-center justify-content-center">
                    <div class="col-12 col-lg-11 col-xl-10">
                    <div class="card-body p-3 p-md-4 p-xl-5">
                        <div class="row">
                        <div class="col-12">
                            <div class="mb-5">
                            <div class="text-center mb-4">
                                <a href="#!">
                                <img src="{% static "images/fevicon.png" %}" alt="BootstrapBrain Logo" width="auto" height="60">
                                </a>
                            </div>
                            <h3 class="text-center">Đăng nhập</h3>
                            </div>
                        </div>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                        <div class="row gy-3 overflow-hidden">
                            <div class="col-12">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
                                <label for="email" class="form-label">Email</label>
                            </div>
                            </div>
                            <div class="col-12">
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name="password" id="password" value="" placeholder="Password" required>
                                <label for="password" class="form-label">Mật khẩu</label>
                            </div>
                            </div>
                            <div class="col-12">
                            {% comment %} <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" name="remember_me" id="remember_me">
                                <label class="form-check-label text-secondary" for="remember_me">
                                Keep me logged in
                                </label>
                            </div> {% endcomment %}
                            </div>
                            <div class="col-12">
                            <div class="d-grid">
                                <button style="color: #fff" class="btn btn-dark btn-outline-primary" type="submit">Đăng nhập ngay</button>
                            </div>
                            </div>
                        </div>
                        </form>
                        <div class="row">
                        <div class="col-12">
                            <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-center mt-5">
                            <a href="{% url 'accounts:user_register' %}" class="link-secondary text-decoration-none">Tạo tài khoản mới</a>
                            <a href="" class="link-secondary text-decoration-none">Quên mật khẩu</a>
                            </div>
                            {% comment %} {% url 'accounts:password_reset' %} {% endcomment %}
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
    {% comment %} <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Login</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
            </div>
            <div class="mt-2 mb-2">
                <small class="">
                    <a class="text-decoration-none text-danger" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
            </small>
        </div>
    </div> {% endcomment %}
{% endblock %}

accounts/templates/manager_login copy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
  </head>
  <body>
    <main class="container">
      <div class="row mt-5 text-capitalize">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <form method="post" class="mt-5 pt-5">
            {% csrf_token %}
            <h2>Dashboard</h2>
            {{ form }}
            <button class="w-100 btn btn-primary mt-3" type="submit">Sign In</button>
          </form>
          <p class="text-muted mt-3"><a href="{% url 'shop:home_page' %}">Back to shop</a></p>
        </div>
        <div class="col-md-4"></div>
      </div>
    </main>
  </body>
</html>

accounts/templates/manager_login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Đăng nhập quản trị</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
	
	<link rel="stylesheet" href="{% static "css/manager_login.css" %}">

	</head>
	<body class="img js-fullheight" style="background-image: url({% static "images/bg.jpg" %});">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Đăng nhập trang Quản trị</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	{% comment %} <h3 class="mb-4 text-center">Have an account?</h3> {% endcomment %}
		      	<form method="post" class="signin-form">
              {% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" name="email" class="form-control" placeholder="Email" required>
		      		</div>
	            <div class="form-group">
	              <input id="password-field" name="password" type="password" class="form-control" placeholder="Mật khẩu" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Đăng nhập</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
		            	<label class="checkbox-wrap checkbox-primary">Ghi nhớ
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'shop:home_page' %}" style="color: #fff">Quay về trang chủ</a>
								</div>
	            </div>
	          </form>
		      </div>
				</div>
			</div>
		</div>
	</section>

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
 
  <!-- poper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- bootstrap js  -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
	
  <script src="{% static 'js/manager_login.js' %}"></script>
	
</body>
</html>

accounts/templates/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            <p class="text-danger">Please enter your email that you used in your account.</p>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-success">
        Your Password Has Been Set.
    </div>
    <a href="{% url 'accounts:user_login' %}" class="">Login Here</a>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/password_reset_done.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-info">
        An Email has been sent with instrunctions to reset your password!
    </div>
{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <!-- CSS Files -->
    <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.2/components/logins/login-8/assets/css/login-8.css" />

{% endblock %}
{% block extend_page %}
    <!-- Login 8 - Bootstrap Brain Component -->
    <section class="bg-light p-3 p-md-4 p-xl-5">
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-xxl-11">
            <div class="card border-light-subtle shadow-sm">
                <div class="row g-0">
                <div class="col-12 col-md-6">
                    <img class="img-fluid rounded-start w-100 h-100 object-fit-contain" loading="lazy" src="{% static "images/iphone-15-promax.png" %}" alt="Welcome back you've been missed!">
                </div>
                <div class="col-12 col-md-6 d-flex align-items-center justify-content-center">
                    <div class="col-12 col-lg-11 col-xl-10">
                    <div class="card-body p-3 p-md-4 p-xl-5">
                        <div class="row">
                        <div class="col-12">
                            <div class="mb-5">
                            <div class="text-center mb-4">
                                <a href="#!">
                                <img src="{% static "images/fevicon.png" %}" alt="BootstrapBrain Logo" width="auto" height="60">
                                </a>
                            </div>
                            <h3 class="text-center">Đăng ký</h3>
                            </div>
                        </div>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                        <div class="row gy-3 overflow-hidden">
                            <div class="col-12">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
                                <label for="email" class="form-label">Email</label>
                            </div>
                            </div>
                            <div class="col-12">
                            <div class="form-floating mb-3">
                                <input type="full_name" class="form-control" name="full_name" id="full_name" value="" placeholder="Họ và tên" required>
                                <label for="full_name" class="form-label">Họ và tên</label>
                            </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating mb-3">
                                    <input type="password" class="form-control" name="password" id="password" value="" placeholder="Password" required>
                                    <label for="password" class="form-label">Mật khẩu</label>
                                </div>
                                </div>
                            <div class="col-12">
                            <div class="d-grid">
                                <button style="color: #fff" class="btn btn-dark btn-outline-primary" type="submit">Tạo tài khoản</button>
                            </div>
                            </div>
                        </div>
                        </form>
                        <div class="row">
                        <div class="col-12">
                            <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-center mt-5">
                                <a href="{% url 'accounts:user_login' %}" class="link-secondary text-decoration-none">Đã có tài khoản</a>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}