accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('products', views.products, name='products'),
    path('products/delete/<int:id>', views.delete_product, name='delete_product'),
    path('products/edit/<int:id>', views.edit_product, name='edit_product'),
    path('orders', views.orders, name='orders'),
    path('orders/detail/<int:id>', views.order_detail, name='order_detail'),
    path('orders/delete/<int:id>', views.delete_order, name='delete_order'),
    path('add-product/', views.add_product, name='add_product'),
    path('add-category/', views.add_category, name='add_category'),
    path('categories', views.categories, name='category'),
    path('categories/delete/<int:id>', views.delete_category, name='delete_category'),
    path('categories/edit/<int:id>', views.edit_category, name='edit_category'),
    path('feedback', views.feedback, name='feedback'),
    path('feedback/detail/<int:id>', views.feedback_detail, name='feedback_detail'),
    path('feedback/delete/<int:id>', views.delete_feedback, name='delete_feedback'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order'),
    path('order/<int:order_id>', views.order_detail, name='order_detail'),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
	path('product/', views.product, name='product'),
	path('contact/', views.contact, name='contact'),
	path('contact/feedback', views.feedback, name='feedback'),
 	path('about-us/', views.about_us, name='about_us'),
]

dashboard/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

from accounts.models import User
from shop.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.full_name} - order id: {self.id}"

    @property
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        return total
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

dashboard/forms.py
from django import forms
from django.forms import ModelForm

from shop.models import Product, Category


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result
    
class AddProductForm(ModelForm):
    upload_images = MultipleFileField()
    class Meta:
        model = Product
        fields = ['category', 'image','upload_images', 'title','description', 'price','quantity']

    def __init__(self, *args, **kwargs):
        super(AddProductForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['id'] = 'summernote'
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class AddCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'image','sub_category', 'is_sub']
    

    def __init__(self, *args, **kwargs):
        super(AddCategoryForm, self).__init__(*args, **kwargs)
        self.fields['is_sub'].widget.attrs['class'] = 'form-check-input'
        self.fields['sub_category'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'


class EditProductForm(ModelForm):
    upload_images = MultipleFileField()
    class Meta:
        model = Product
        fields = ['category', 'image','upload_images', 'title','description', 'price','quantity']

    def __init__(self, *args, **kwargs):
        super(EditProductForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['id'] = 'summernote'
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            
class EditCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'image','sub_category', 'is_sub']

    def __init__(self, *args, **kwargs):
        super(EditCategoryForm, self).__init__(*args, **kwargs)
        self.fields['is_sub'].widget.attrs['class'] = 'form-check-input'
        self.fields['sub_category'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'
            

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404

from shop.models import Product, ProductImage, Category, Feedback
from accounts.models import User
from orders.models import Order, OrderItem
from .forms import *



def is_manager(user):
    try:
        if not user.is_manager:
            raise Http404
        return True
    except:
        raise Http404


@user_passes_test(is_manager)
@login_required
def products(request):
    products = Product.objects.all()
    context = {'title':'Sản phẩm' ,'products':products}
    return render(request, 'products.html', context)


@user_passes_test(is_manager)
@login_required
def categories(request):
    categories = Category.objects.all()
    context = {'title':'Nhãn hàng' ,'categories':categories}
    return render(request, 'categories.html', context)


@user_passes_test(is_manager)
@login_required
def feedback(request):
    feedbacks = Feedback.objects.all()
    context = {'title':'Góp ý' ,'feedbacks':feedbacks}
    return render(request, 'feedback.html', context)


@user_passes_test(is_manager)
@login_required
def add_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        files = request.FILES.getlist("upload_images")
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            for i in files:
                ProductImage.objects.create(product=f, image=i)
            messages.success(request, 'Sản phẩm đã được thêm vào')
            return redirect('dashboard:add_product')
    else:
        form = AddProductForm()
    context = {'title':'Thêm sản phẩm', 'form':form}
    return render(request, 'add_product.html', context)


@user_passes_test(is_manager)
@login_required
def delete_product(request, id):
    product = Product.objects.filter(id=id).delete()
    messages.success(request, 'Sản phẩm đã bị xóa', 'success')
    return redirect('dashboard:products')


@user_passes_test(is_manager)
@login_required
def edit_product(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sản phẩm đã được cập nhật', 'success')
            return redirect('dashboard:products')
    else:
        form = EditProductForm(instance=product)
    context = {'title': 'Sửa sản phẩm', 'form':form}
    return render(request, 'edit_product.html', context)


@user_passes_test(is_manager)
@login_required
def add_category(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            print('kkkkk')
            form.save()
            messages.success(request, 'Nhãn hàng đã được thêm vào')
            return redirect('dashboard:add_category')
        else:
            context = {'title':'Thêm nhãn hàng', 'form':form}
            return render(request, 'add_category.html', context)
    else:
        form = AddCategoryForm()
    context = {'title':'Thêm nhãn hàng', 'form':form}
    return render(request, 'add_category.html', context)


@user_passes_test(is_manager)
@login_required
def delete_category(request, id):
    category = Category.objects.filter(id=id).delete()
    messages.success(request, 'Nhãn hàng đã bị xóa', 'success')
    return redirect('dashboard:category')


@user_passes_test(is_manager)
@login_required
def edit_category(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'POST':
        form = EditCategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Nhãn hàng đã được cập nhật', 'success')
            return redirect('dashboard:category')
    else:
        form = EditCategoryForm(instance=category)
    context = {'title': 'Sửa nhãn hàng', 'form':form}
    return render(request, 'edit_category.html', context)


@user_passes_test(is_manager)
@login_required
def orders(request):
    orders = Order.objects.all()
    context = {'title':'Đơn hàng', 'orders':orders}
    return render(request, 'orders.html', context)


@user_passes_test(is_manager)
@login_required
def order_detail(request, id):
    order = Order.objects.filter(id=id).first()
    items = OrderItem.objects.filter(order=order).all()
    context = {'title':'Chi tiết đơn hàng', 'items':items, 'order':order}
    return render(request, 'order_detail.html', context)


@user_passes_test(is_manager)
@login_required
def delete_order(request, id):
    order = Order.objects.filter(id=id).delete()
    messages.success(request, 'Đơn hàng đã bị xóa', 'success')
    return redirect('dashboard:orders')


@user_passes_test(is_manager)
@login_required
def delete_feedback(request, id):
    feedback = Feedback.objects.filter(id=id).delete()
    messages.success(request, 'Feedback đã bị xóa', 'success')
    return redirect('dashboard:feedback')


@user_passes_test(is_manager)
@login_required
def feedback_detail(request, id):
    feedback = Feedback.objects.filter(id=id).all()
    context = {'title':'Thông tin chi tiết Feedback', 'feedback':feedback}
    return render(request, 'feedback_detail.html', context)

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST
from django.utils import timezone

from .models import Order, OrderItem
from cart.utils.cart import Cart

@login_required
def create_order(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(
            order=order, product=item['product'],
            price=item['price'], quantity=item['quantity'])
    return redirect('orders:pay_order', order_id=order.id)


@login_required
def checkout(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Checkout' ,'order':order}
    return render(request, 'checkout.html', context)


@login_required
def fake_payment(request, order_id):
    cart = Cart(request)
    cart.clear()
    order = get_object_or_404(Order, id=order_id)
    order.status = True
    order.save()
    return redirect('orders:user_orders')


@login_required
def user_orders(request):
    orders = request.user.orders.all()
    context = {'title':'Orders', 'orders': orders}
    return render(request, 'user_orders.html', context)

@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Chi tiết đơn hàng' ,'order':order}
    return render(request, 'order_detail.html', context)

dashboard/templates/add_category.html
{% extends "dashboard.html" %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

{% endblock %}

dashboard/templates/add_product.html
{% extends "dashboard.html" %}
{% load static %}

{% block script %}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
{% endblock %}

{% block content %}
    
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>
{% endblock %}

dashboard/templates/categories.html
{% extends "dashboard.html" %}

{% block content %}

<table class="table table-striped ">
    <thead class="thead-dark">
        <tr>
            <th scope="col">STT</th>
            <th scope="col">Ảnh</th>
            <th scope="col">Tên</th>
            {% comment %} <th scope="col">Phân Loại</th>
            <th scope="col">Số lượng</th> {% endcomment %}
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    {% for category in categories %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ category.image }}</td>
        <td>{{ category.title }}</td>
        {% comment %} <td>{{ product.category }}</td> {% endcomment %}
        {% comment %} <td>{{ product.date_created|date:"M d" }}</td> {% endcomment %}
        <td><a class="text-danger text-decoration-none" href="{% url 'dashboard:delete_category' category.id %}">Xóa</a></td>
        <td><a class="text-info text-decoration-none" href="{% url 'dashboard:edit_category' category.id %}">Sửa</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>

{% endblock %}

dashboard/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap_dashboard.css' %}" />
    <script src="{% static 'js/bootstrap_dashboard.js' %}"></script>
    {% block script %}{% endblock %}
    <title>{{title}}</title>
</head>
<body>
    <div class="row mt-5">
        <div class="col-md-1"></div>
        <!-- content -->
        <div class="col-md-7">
            <h2 class="border-bottom text-capitalize">{{ title }}</h2>
            <div class="p-4">
                <!-- messages -->
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <!-- sidebar -->
        <div class="col-md-3 border-start">
            <h3 class="text-muted">Menu</h3>
            <a class="text-decoration-none" href="{% url 'dashboard:products' %}">
                <li class="rounded list-group-item  text-primary">Sản phẩm</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:category' %}">
                <li class="rounded list-group-item mt-2  text-primary">Nhãn hàng</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:add_product' %}">
                <li class="rounded list-group-item mt-2 text-primary">Thêm sản phẩm mới</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:add_category' %}">
                <li class="rounded list-group-item mt-2  text-primary">Thêm nhãn hàng mới</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:orders' %}">
                <li class="rounded list-group-item mt-2  text-primary">Đơn hàng</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:feedback' %}">
                <li class="rounded list-group-item mt-2  text-primary">Góp ý</li>
            </a>
            <hr>
            <a class="text-decoration-none" href="{% url 'shop:home_page' %}">
                <li class="rounded list-group-item bg-primary mt-2  text-white">Quay lại shop</li>
            </a>
            <a class="text-decoration-none" href="{% url 'accounts:user_logout' %}">
                <li class="rounded list-group-item bg-danger mt-2  text-white">Đăng xuất</li>
            </a>
            <div class="text-muted mt-2">Bạn đang đăng nhập với: {{ request.user.email }}</div>
        </div>
        <div class="col-md-1 "></div>
    </div>
</body>
</html>

dashboard/templates/edit_category.html
{% extends "dashboard.html" %}
{% load static %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>

{% endblock %}

dashboard/templates/edit_product.html
{% extends "dashboard.html" %}
{% block content %}

{% block script %}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
{% endblock %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>

{% endblock %}

dashboard/templates/feedback.html
{% extends "dashboard.html" %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tên Khách Hàng</th>
        <th scope="col">Tiêu đề</th>
        <th scope="col">Email</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for feedback in feedbacks %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ feedback.customer_name }}</td>
        <td>{{ feedback.title }}</td>
        <td>{{ feedback.email }}</td>
        <td><a href="{% url 'dashboard:feedback_detail' feedback.id %}" class="text-primary text-decoration-none">Detail</a></td>
        <td><a class="text-danger text-decoration-none" href="{% url 'dashboard:delete_feedback' feedback.id %}">Xóa</a></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  

{% endblock %}

dashboard/templates/feedback_detail.html
{% extends "dashboard.html" %}

{% block content %}
{% for item in feedback  %}
<div class="bg-light rounded border-bottom p-3">
    <p>Tên khách hàng: {{item.customer_name}}</p>
    <p>Email: {{item.email}}</p>
    <p>Tiêu đề: {{item.title}}</p>
    <p>Nội dung: {{item.comment}}</p>
</div>
{% endfor %}
{% endblock %}

dashboard/templates/order_detail.html
{% extends "dashboard.html" %}

{% block content %}
{% if order.status %}
    <h4><b class="text-success">Successful</b></h4>
{% else %}
    <h3><b class="text-danger">Cancelled</b></h3>
{% endif %}
{% for item in items  %}
<div class="bg-light rounded border-bottom p-3">
    <p>product:<a class="text-decoration-none" href="{{ item.product.get_absolute_url }}"> {{item.product.title}}</a></p>
    <p>Price: ${{item.price}}</p>
    <p>quantity: {{item.quantity}}</p>
</div>
{% endfor %}
<h4 class="border-top pt-2 text-muted">Total: ${{ order.get_total_price }}</h4>

{% endblock %}

dashboard/templates/orders.html
{% extends "dashboard.html" %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Khách hàng</th>
        <th scope="col">Id</th>
        <th scope="col">Tổng tiền</th>
        <th scope="col">Trạng thái</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for order in orders %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ order.user.full_name }}</td>
        <td>{{ order.id }}</td>
        <td>${{ order.get_total_price }}</td>
        {% if order.status %}
            <td class="text-success">Hoàn thành</td>
        {% else %}
            <td class="text-danger">Bị hủy</td>
        {% endif %}
        <td><a href="{% url 'dashboard:order_detail' order.id %}" class="text-primary text-decoration-none">Chi tiết</a></td>
        <td><a class="text-danger text-decoration-none" href="{% url 'dashboard:delete_order' order.id %}">Xóa</a></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  

{% endblock %}

dashboard/templates/products.html
{% extends "dashboard.html" %}

{% block content %}

<table class="table table-striped ">
    <thead class="thead-dark">
        <tr>
            <th scope="col">STT</th>
            <th scope="col">Tên</th>
            <th scope="col">Giá</th>
            <th scope="col">Phân Loại</th>
            <th scope="col">Số lượng</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    {% for product in products %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
        <td>${{ product.price }}</td>
        <td>{{ product.category }}</td>
        {% comment %} <td>{{ product.date_created|date:"M d" }}</td> {% endcomment %}
        <td>{{ product.quantity }}</td>
        <td><a class="text-danger text-decoration-none" href="{% url 'dashboard:delete_product' product.id %}">Xóa</a></td>
        <td><a class="text-info text-decoration-none" href="{% url 'dashboard:edit_product' product.id %}">Sửa</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>

{% endblock %}